# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area
# workspace = 1, monitor:DP-1
# workspace = 2, monitor:DP-1
# workspace = 3, monitor:DP-1
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1

# HDMI port: mirror display. To see device name, use `hyprctl monitors`
source = ./noctalia.conf
source = ~/.config/hypr/hyprland-gui.conf

input {
    # midle button scroll / autoscrolling
    scroll_method = on_button_down
    scroll_button = 274

    touchpad {
        clickfinger_behavior = false
    }
}

xwayland {
  force_zero_scaling = true
}

ecosystem {
  enforce_permissions = true
}

general {
  gaps_in = 5
  gaps_out = 7
  border_size = 3
  layout = scrolling
}

layerrule {
  name = noctalia
  match:namespace = noctalia-background-.*$
  ignore_alpha = 0.5
  blur = true
  blur_popups = true
}

decoration {
    blur {
      enabled = true
      size = 10
      passes = 1
      brightness = 0.5
      xray = off
  }
}
