##============
# Noctalia
##============

$ipc = qs -c noctalia-shell ipc call

##! Core binds
bind = SUPER, comma, exec, $ipc settings toggle

bindel = , XF86MonBrightnessUp, exec, $ipc brightness increase
bindel = , XF86MonBrightnessDown, exec, $ipc brightness decrease

# Launcher
bind = SUPER, SUPER_L, exec, $ipc launcher toggle
bind = SUPER, SUPER_R, exec, $ipc launcher toggle
bind = Super, Period, exec, $ipc launcher emoji
bind = Super, V, exec, $ipc launcher clipboard

# Sleep & session Menu
bind = Super, L, exec, $ipc sessionMenu lockAndSuspend
bindl = , switch:Lid Switch, exec, qs -c noctalia-shell ipc call lockScreen lock
unbind = Super+Shift, L
bind = Super+Shift, L, exec, $ipc sessionMenu toggle

##! Screen Shot, Records, & more
# screenshot Full Screen
unbind = SUPER, S
bind = SUPER, S, exec, $ipc plugin:screen-shot-and-record screenshot
# Annotate, could be used for screenshot too
bind = SUPER+Shift, S, exec, $ipc plugin:screen-shot-and-record screenshot
# Lens
# bind = Super+Shift, A, exec, $ipc plugin:screen-toolkit lens
bind = Super+Shift, A, exec, ~/.config/hypr/hyprland/scripts/snip_to_search.sh # [hidden] Google Lens (fallback)
# OCR
# Character recognition
bind = Super+Shift, X, exec, $ipc plugin:screen-toolkit ocr
# Screen Record
bind = SUPER, R, exec, qs -c noctalia-shell ipc call plugin:screen-recorder toggle
