# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/
layerrule = match:namespace noctalia-shell:regionSelector, no_anim on

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
windowrule = opacity 0.89 override 0.89 override, match:class .*

# Enable blur for all apps
windowrule = match:class .*, no_blur off

# kdeconnect
windowrule = match:class ^(org.kde.kdeconnect.app)$, float on
windowrule = center on, match:class ^(org.kde.kdeconnect.app)$
windowrule = size 900 600, match:class ^(org.kde.kdeconnect.app)$

# BTOP
windowrule = match:title ^(btop)$, float on
windowrule = center on, match:title ^(btop)$
windowrule = size 900 600, match:title ^(btop)$

windowrule = match:title ^(fish)$, float on
windowrule = center on, match:title ^(fish)$
windowrule = size 900 600, match:title ^(fish)$

# Proton Pass
windowrule = match:class ^(Proton Pass)$, float on
windowrule = center on, match:class ^(Proton Pass)$
windowrule = size 0.5 0.5, match:class ^(Proton Pass)$

# Special Workspace
windowrule = workspace special:communications, match:class discord|equibop|vesktop
windowrule = size 0.7 1, match:class discord|equibop|vesktop
windowrule = workspace special:communications, match:initial_title ^(ZapZap)$
windowrule = size 0.7 1, match:initial_title ^(ZapZap)$

# persistent workspace & assign spesific monitor for it
workspace = 1, monitor:DP-1
# workspace = 2, monitor:DP-1
# workspace = 3, monitor:DP-1
workspace = 1, persistent:true
workspace = 2, persistent:true
workspace = 3, persistent:true
workspace = 4, persistent:true
workspace = 5, persistent:true
workspace = 6, persistent:true
workspace = 7, persistent:true, monitor:HDMI-A-1
workspace = 8, persistent:true, monitor:HDMI-A-1
workspace = 9, persistent:true, monitor:HDMI-A-1

#--------------
# Permission
#--------------

# Screen Capture
#---------------

# Allow xdg-desktop-hyprland
permission = /usr/(lib|libexec|lib64)/xdg-desktop-hyprland, screencopy, allow
# Allow grim
permission = /usr/bin/grim, screencopy, allow
# Allow quickshell
permission = /usr/bin/quickshell, screencopy, allow
# Allow hyprlock
permission = /usr/bin/hyprlock, screencopy, allow

# keyboard
#----------

# Allow internal laptop keyboard
permission = at-translated-set-2-keyboard, keyboard, allow
# Allow other internal devices (buttons, ThinkPad extras, etc.)
permission = video-bus|power-button|sleep-button|thinkpad-extra-buttons, keyboard, allow
# Allow mouse, from gamen, main mouse
permission = instant-usb-gaming-mouse--keyboard, keyboard, allow
# Allow mouse, from redragon, secondary mouse
permission = mosart-semi.-2.4g-input-device-consumer-control, keyboard, allow
permission = mosart-semi.-2.4g-input-device, keyboard, allow
permission = mosart-semi.-2.4g-input-device-system-control, keyboard, allow
# Allow ydotoold
permission = ydotoold-virtual-device, keyboard, allow
# Allow keyd
permission = keyd-virtual-keyboard, keyboard, allow
# All other keyboards (external) will always ask for permission
permission = .*, keyboard, ask
