# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1

# kdeconnect
windowrule = match:class ^(org.kde.kdeconnect.app)$, float on
windowrule = size 60% 70%, match:class ^(org.kde.kdeconnect.app)$

# Special Workspace
windowrule = workspace special:discord, match:class discord|equibop|vesktop
windowrule = workspace special:whatsapp, match:initial_title ^(ZapZap)$

#--------------
# Permission
#--------------

# Screen Capture
#---------------

# Allow xdg-desktop-hyprland
permission = /usr/(lib|libexec|lib64)/xdg-desktop-hyprland, screencopy, allow
# Allow grim
permission = /usr/bin/grim, screencopy, allow
# Allow quickshell
permission = /usr/bin/quickshell, screencopy, allow

##keyboard
#----------

# Allow internal laptop keyboard
permission = at-translated-set-2-keyboard, keyboard, allow
# Allow other internal devices (buttons, ThinkPad extras, etc.)
permission = video-bus|power-button|sleep-button|thinkpad-extra-buttons, keyboard, allow
# Allow mouse, from gamen, main mouse
permission = instant-usb-gaming-mouse--keyboard, keyboard, allow
# Allow ydotoold
permission = ydotoold-virtual-device, keyboard, allow
# Allow keyd
permission = keyd-virtual-keyboard, keyboard, allow
# All other keyboards (external) will always ask for permission
permission = .*, keyboard, ask
