[ids]

*

[main]

# Maps prtsc to leftmeta
sysrq = rightmeta
alt = oneshot(alt)
rightalt = oneshot(alt)

#--------------------------------------------------------------------------------------------
# overloaded key. have to be here(above other layer), otherwise it'll registered inside a layer
#--------------------------------------------------------------------------------------------

# Maps capslock to escape when pressed and control when held. VIM Mode Like
capslock = overload(ctrl_vim, esc)

# Maps tab to super/meta on held but still tab on press
# tab = overload(meta, tab)

# Maps z to a custom layer, but just 'z' when pressed.
z = overload(z, z)

# remap homepage key to comma
homepage = overload(control, comma)
# remap mail key to space
mail = space
# make calculator key to launch rofi-calc (only works using config)
calc = M-S-c

#---------------
# VIM Mode Like
#---------------

# ctrl_vim modifier layer; inherits from 'Ctrl' modifier layer
[ctrl_vim:C]

space = toggle(vim_mode)
esc = swap(macro_mode)

# vim_mode layer
[vim_mode]

esc = capslock

h = left
j = down
k = up
l = right
# forward word
w = C-right
# backward word
b = C-left

# macro_mode modifier layer
[macro_mode:C]
i = macro(testing)

## Emails
g = macro(danishhusam@gmail.com)
e = macro(husam.danish@proton.me)

## macro
p = macro(Husam space Danish)
n = macro(5027251060)
insert = macro(089667867905)
t = macro(Teknologi space Informasi)
u = macro(Institut space Teknologi space Sepuluh space Nopember)


## Media / modifier
# m = oneshot(media)

# [media]
#
# j = previoussong
# k = playpause
# l = nextsong
