[ids]

*

[main]

# Maps prtsc to leftmeta
sysrq = rightmeta
alt = oneshot(alt)
rightalt = oneshot(alt)

#--------------------------------------------------------------------------------------------
# overloaded key. have to be here(above other layer), otherwise it'll registered inside a layer
#--------------------------------------------------------------------------------------------

# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)

# Maps tab to super/meta on held but still tab on press
# tab = overload(meta, tab)

# Maps z to a custom layer, but just 'z' when pressed.
z = overload(z, z)

# remap homepage key to comma
homepage = overload(control, comma)
# remap mail key to space
mail = space
# make calculator key to launch rofi-calc (only works using config)
calc = M-S-c


esc = capslock


## Emails
g = macro(danishhusam@gmail.com)
e = macro(husam.danish@proton.me)

## macro
p = macro(Husam space Danish)
n = macro(5027251060)
insert = macro(089667867905)
t = macro(Teknologi space Informasi)
u = macro(Institut space Teknologi space Sepuluh space Nopember)


## Media / modifier
# m = oneshot(media)

# [media]
#
# j = previoussong
# k = playpause
# l = nextsong
